### ISSUE TITLE
Support for webworkers

### ISSUE THREAD

**Issue by drcmda** [daniellmb/perfnow.js#4]
There is no window context in workers, the polyfill fails. )-:

**Comment by daniellmb** [comment]
I believe this is [supported in Chrome](https://src.chromium.org/viewvc/blink/trunk/Source/platform/RuntimeEnabledFeatures.in?r1=166435&r2=166434&pathrev=166435), what browser did you try this on? But yeah, it should be possible to modify the script to properly fall back to `Date.now`.

**Comment by daniellmb** [comment]
Published under version 0.2.0 you can [see it in action here](http://codepen.io/daniellmb/pen/zqoOgJ?editors=1010).
